projects:
  AppSyncChat:
    schemaPath: appsyncchatlibrary/src/main/graphql/schema.json
    includes:
      - appsyncchatlibrary/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: >-
          appsyncchatlibrary/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: ap-northeast-1
        apiId: v64judyrv5gc3lkp5rrgai7vkm
        maxDepth: 2
